blank_issues_enabled: false
contact_links:
  - name: ✏️ FAQ
    url: https://telegra.ph/first-store-FAQ-09-19
    about: Read the frequently asked questions, maybe it will help solve your problem right now.